Update Aeon

diff --git a/Aeon b/Aeon
--- a/Aeon
+++ b/Aeon
@@ -1,82 +1,122 @@
-#!/bin/sh
+#!/bin/bash
 
-# Update and upgrade packages
-apt-get update && apt-get upgrade -y
+# Update system (No apt-get, use apk)
+update_system() {
+    apk update && apk upgrade
+}
 
-# Install necessary repositories and Python 3.12
-apt-get install -y software-properties-common
-add-apt-repository ppa:deadsnakes/ppa
-apt-get update
-apt-get install -y python3.12 python3.12-dev python3.12-venv python3-pip libpython3.12 libpython3.12-dev
+# Install Python 3.12 and dependencies
+install_python() {
+    apk add --no-cache python3 py3-pip python3-dev
+    pip install --upgrade pip
+}
 
-# Install additional dependencies
-apt-get install -y --no-install-recommends \
-    apt-utils aria2 curl zstd git libmagic-dev \
-    locales mediainfo neofetch p7zip-full \
-    p7zip-rar tzdata wget qbittorrent-nox \
-    autoconf automake build-essential cmake \
-    g++ gcc gettext gpg-agent intltool libtool \
-    make unzip zip autoconf automake libtool \
-    libcurl4-openssl-dev libsodium-dev libssl-dev \
-    libcrypto++-dev libc-ares-dev libsqlite3-dev \
-    libfreeimage-dev swig libboost-all-dev \
-    libpthread-stubs0-dev zlib1g-dev
+# Install additional system dependencies
+install_dependencies() {
+    apk add --no-cache \
+        aria2 curl git libmagic-dev locales mediainfo neofetch \
+        p7zip tzdata wget autoconf automake build-base cmake \
+        gettext gpgme intltool libtool make unzip zip \
+        openssl-dev libc-dev zlib-dev boost-dev
+}
 
-# Create temporary directory and install FFmpeg
-mkdir /Temp
-cd /Temp
-wget https://github.com/arakurumi/FFmpeg-Builds/releases/download/latest/ffmpeg-n7.1-latest-linux64-nonfree-7.1.tar.xz
-7z x ffmpeg-n7.1-latest-linux64-nonfree-7.1.tar.xz
-7z x ffmpeg-n7.1-latest-linux64-nonfree-7.1.tar
-cd /Temp/ffmpeg-n7.1-latest-linux64-nonfree-7.1/bin
-mv ffmpeg /usr/bin/xtra
-mv ffprobe /usr/bin/ffprobe
-mv ffplay /usr/bin/ffplay
-chmod +x /usr/bin/xtra /usr/bin/ffprobe /usr/bin/ffplay
+# Download and install qbittorrent-nox
+install_qbittorrent() {
+    ARCH=$(uname -m)
+    mkdir -p /usr/local/bin
+
+    case "$ARCH" in
+        x86_64)
+            wget -qO /usr/local/bin/xnox https://github.com/userdocs/qbittorrent-nox-static/releases/latest/download/x86_64-qbittorrent-nox
+            ;;
+        aarch64)
+            wget -qO /usr/local/bin/xnox https://github.com/userdocs/qbittorrent-nox-static/releases/latest/download/aarch64-qbittorrent-nox
+            ;;
+        *)
+            echo "Unsupported architecture for qbittorrent-nox: $ARCH"
+            exit 1
+            ;;
+    esac
+
+    chmod +x /usr/local/bin/xnox
+}
+
+# Install FFmpeg
+install_ffmpeg() {
+    ARCH=$(uname -m)
+    mkdir -p /Temp
+    cd /Temp
+
+    case "$ARCH" in
+        x86_64)
+            wget https://github.com/5hojib/FFmpeg-Builds/releases/download/latest/ffmpeg-n7.1-latest-linux64-gpl-7.1.tar.xz
+            ;;
+        aarch64)
+            wget https://github.com/5hojib/FFmpeg-Builds/releases/latest/download/ffmpeg-n7.1-latest-linuxarm64-gpl-7.1.tar.xz
+            ;;
+        *)
+            echo "Unsupported architecture for FFmpeg: $ARCH"
+            exit 1
+            ;;
+    esac
+
+    tar -xJf ffmpeg-n7.1-latest-linux*-gpl-7.1.tar.xz
+    tar -xf ffmpeg-n7.1-latest-linux*-gpl-7.1.tar
+    mv ./ffmpeg-n7.1-latest-linux*/bin/* /usr/bin/
+    chmod +x /usr/bin/*
+}
 
 # Install rclone and rename binaries
-cd /Temp
-curl https://rclone.org/install.sh | bash
+install_rclone() {
+    curl https://rclone.org/install.sh | bash
+    mv /usr/bin/rclone /usr/bin/xone
+    mv /usr/bin/aria2c /usr/bin/xria
+}
 
-# rename binaries
-mv /usr/bin/rclone /usr/bin/xone
-mv /usr/bin/aria2c /usr/bin/xria
-mv /usr/bin/qbittorrent-nox /usr/bin/xnox
+# Install Python packages
+install_python_packages() {
+    pip install --no-cache-dir -U setuptools uv
+
+    pip install --no-cache-dir \
+        aiofiles aioshutil anytree apscheduler aria2p asyncio \
+        cloudscraper dnspython feedparser flask gevent \
+        google-api-python-client google-auth-httplib2 google-auth-oauthlib \
+        gunicorn httpx lxml motor natsort pillow psutil \
+        pymongo python-dotenv python-magic qbittorrent-api requests \
+        telegraph tenacity urllib3 uvloop xattr yt-dlp[default,curl-cffi] \
+        tgcrypto pyrofork
+}
 
 # Clone and build MEGA SDK
-git clone https://github.com/meganz/sdk.git --depth=1 -b v4.8.0 /home/sdk
-cd /home/sdk
-rm -rf .git
-autoupdate -fIv && ./autogen.sh
-./configure --disable-silent-rules --enable-python --with-sodium --disable-examples
-make -j$(nproc --all)
+build_mega_sdk() {
+    git clone https://github.com/meganz/sdk.git --depth=1 -b v4.8.0 /home/sdk
+    cd /home/sdk
+    rm -rf .git
+    ./autogen.sh
+    ./configure --disable-silent-rules --enable-python --with-sodium --disable-examples
+    make -j$(nproc)
 
-# Build and install the MEGA SDK Python bindings
-cd bindings/python/
-python3.12 setup.py bdist_wheel
-pip3 install --break-system-packages --no-cache-dir dist/megasdk-4.8.0-*.whl
-pip3 install --break-system-packages --ignore-installed --no-cache-dir \
-    aiofiles aioshutil anytree apscheduler aria2p asyncio \
-    cloudscraper dnspython feedparser flask gevent \
-    google-api-python-client google-auth-httplib2 google-auth-oauthlib \
-    gunicorn httpx lxml motor natsort pillow psutil \
-    pymongo python-dotenv python-magic qbittorrent-api requests \
-    telegraph tenacity urllib3 uvloop xattr yt-dlp[default] \
-    tgcrypto pyrofork==2.2.11
+    cd bindings/python/
+    python3 setup.py bdist_wheel
+    pip install --no-cache-dir dist/megasdk-4.8.0-*.whl
+}
 
-# Clean up unnecessary packages
-apt-get remove -y \
-    autoconf automake build-essential \
-    cmake g++ gcc gettext gpg-agent \
-    intltool libtool make unzip zip \
-    libtool libcurl4-openssl-dev libssl-dev \
-    libc-ares-dev libsqlite3-dev swig \
-    libboost-all-dev libpthread-stubs0-dev zlib1g-dev
+# Clean up
+cleanup() {
+    rm -rf /Temp Aeon Dockerfile
+}
 
-apt-get autoremove -y
-apt-get autoclean -y
+# Main script
+main() {
+    update_system
+    install_python
+    install_dependencies
+    install_qbittorrent
+    install_ffmpeg
+    install_rclone
+    install_python_packages
+    build_mega_sdk
+    cleanup
+}
 
-# Clean up temporary directories and files
-rm -rf /Temp
-rm -rf Aeon
-rm -rf Dockerfile
+main
